language: python
# services:
  # - go
  # - singularity
python:
  # - "2.7"
  - "3.5"

cache:
  directories: 
    - $HOME/.pip
    - /opt/singularity

# addons:
#   apt:
#     packages:
#       - flawfinder
#       - squashfs-tools
#       - uuid-dev
#       - libuuid1
#       - libffi-dev
#       - libssl-dev
#       - libssl1.0.0
#       - libarchive-dev
#       - libgpgme11-dev
#       - libseccomp-dev
#       -

before_install:
  - gimme 1.13.5
  - eval "$(gimme 1.13.5)"
  - bash install_singular.sh
  - pip install .
install:
  - echo pass
script:
  - singularity pull docker://python:2.7.17-alpine
  - python test.py



# before_install:
# - docker pull carlad/sinatra
# - docker run -d -p 127.0.0.1:80:4567 carlad/sinatra /bin/sh -c "cd /root/sinatra; bundle exec foreman start;"
# - docker ps -a
# - docker run carlad/sinatra /bin/sh -c "cd /root/sinatra; bundle exec rake test"

# script:
# - bundle exec rake test  
# docker://quay.io/singularity/singularity:v3.5.3-slim