language: python
# services:
  # - go
  # - singularity
python:
  # - "2.7"
  - "3.5"

cache:
  directories: 
    - $HOME/.pip
    - $HOME/.singularity
    - /opt/singularity

before_install:
  - gimme 1.13.5
  - eval "$(gimme 1.13.5)"
  - bash install_singular.sh
install:
  - echo pass
script:
  # - singularity pull docker://alpine:lastest
  - singularity exec docker://python:2.7.17-alpine python -V
  - sudo -E python -V
  - sudo -E pip install .
  - sudo -E python test.py
  # - ls -lhtr /deps/*
  # - tree /deps



# before_install:
# - docker pull carlad/sinatra
# - docker run -d -p 127.0.0.1:80:4567 carlad/sinatra /bin/sh -c "cd /root/sinatra; bundle exec foreman start;"
# - docker ps -a
# - docker run carlad/sinatra /bin/sh -c "cd /root/sinatra; bundle exec rake test"

# script:
# - bundle exec rake test  
# docker://quay.io/singularity/singularity:v3.5.3-slim